<?php 
return array(
  'title' => 'string',
  'description' => 'string',
	'author'=>array(
		'name' => 'string',
		'biblo' => 'string',
	),
	'offer'=> array(
		'activation_date' => 'date',
		'affiliate_network_code' => 'string',
		'affiliate_network_id' => 'integer',
		'brand_board_id' => 'integer',
		'brand_id' => 'integer',
		'brand_name' => 'string',
		'expiration_date' => 'date',
		'headline' => 'string',
		'id' => 'integer',
		'market' => 'string',
		'merchant' => 'string',
		'scope' => 'string',
		'skew_age_from' => 'string',
		'skew_age_to' => 'string',
		'skew_gender' => 'string',
		'skew_product_quality' => 'string',
		'skew_relative_quality' => 'string',
		'source' => 'string',
		'url' => 'string',
		'with_coupon' => 'string',
	),
	'context'=>array(
		'application' => 'string',
		'auto_follow' => 'string',
		'bk_email' => 'string',
		'brand_execluded' => 'string',
		'category_id' => 'integer',
		'category_name' => 'string',
		'clicked_from' => 'string',
		'connected_email' => 'string',
		'created_at' => 'date',
		'current_source' => 'string',
		'estimate_response_time' => 'date',
		'event' => 'string',
		'homepage_version' => 'string',
		'item' => 'string',
		'login_with' => 'string',
		'page_rendered' => 'string',
		'page_title' => 'string',
		'pages_viewed' => 'string',
		'post_title' => 'string',
		'referrer' => 'string',
		'request_completion' => 'string',
		'request_type' => 'string',
		'search_engine_query' => 'string',
		'search_term' => 'string',
		'session_id' => 'string',
		'shared_on' => 'string',
		'signup_button_location' => 'string',
		'signup_with' => 'string',
		'subid' => 'string',
		'uri' => 'string',
		'user_ip' => 'string',
		'viewed_at' => 'date',
		'viewed_from' => 'string',
	),
	'platform'=>array(
		'browser' => 'string',
		'browser_version' => 'string',
		'device' => 'string',
		'operator' => 'string',
		'os' => 'string',
		'os_version' => 'string',
		'product_subtype' => 'string',
		'product_type' => 'string',
	),
	'board' =>array(
		'brand_id' => 'integer',
		'category_id' => 'integer',
		'id' => 'integer',
		'name' => 'string',
		'type' => 'string',
	)
);
