<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'The verification code is incorrect.' => 'رمز التأكيد غير صحيح.',
  'Please fix the following input errors:' => 'الرجاء إصلاح الأخطاء التالية :',
  '{attribute} cannot be blank.' => '{attribute} لا يَجوز أن يكون فارغا.',
  'Get a new code' => 'توليد صورة جديدة',
  'Go to page: ' => 'الذهاب إلى الصفحة :',
  '&lt;&lt; First' => '&lt;&lt; الأولى',
  '&lt; Previous' => '&lt; السابقة',
  'Next &gt;' => 'التالية &gt;',
  '{attribute} must be repeated exactly.' => '{attribute} يجب أن بتطابق.',
  '{attribute} "{value}" has already been taken.' => '{attribute} « {value} » مستخدم من غيرك',
);
